# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_11:
    has_velocity_limits: true
    max_velocity: 3.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint_12:
    has_velocity_limits: true
    max_velocity: 3.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint_13:
    has_velocity_limits: true
    max_velocity: 3.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint_21:
    has_velocity_limits: true
    max_velocity: 3.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint_22:
    has_velocity_limits: true
    max_velocity: 3.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint_23:
    has_velocity_limits: true
    max_velocity: 3.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint_31:
    has_velocity_limits: true
    max_velocity: 3.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint_32:
    has_velocity_limits: true
    max_velocity: 3.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint_33:
    has_velocity_limits: true
    max_velocity: 3.0
    has_acceleration_limits: false
    max_acceleration: 0
  joint_41:
    has_velocity_limits: true
    max_velocity: 3.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint_42:
    has_velocity_limits: true
    max_velocity: 3.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint_43:
    has_velocity_limits: true
    max_velocity: 3.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint_51:
    has_velocity_limits: true
    max_velocity: 3.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint_52:
    has_velocity_limits: true
    max_velocity: 3.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint_53:
    has_velocity_limits: true
    max_velocity: 3.0
    has_acceleration_limits: false
    max_acceleration: 0
  joint_61:
    has_velocity_limits: true
    max_velocity: 3.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint_62:
    has_velocity_limits: true
    max_velocity: 3.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint_63:
    has_velocity_limits: true
    max_velocity: 3.0
    has_acceleration_limits: false
    max_acceleration: 0
